language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install coverage coveralls
script:
- coverage run --source=semanticuiform setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: MaHarder
  password:
    secure: pypi-AgEIcHlwaS5vcmcCJGVmMjI1ODIyLWU0YTQtNDRhZS05ZTUzLThjZDVmNTZkZWY5MgACSHsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJkamFuZ28yLXNlbWFudGljdWktZm9ybSJdfSwgInZlcnNpb24iOiAxfQAABiABZNePs-zIfHzJo4UcUHDJ3UxB8bMk3zgv9NoUz5KAVA
  on:
    repo: MaHarder/django2-semanticui-form
  distributions: "sdist bdist_wheel"
